version: "1"
services:
    crud-service:
        build:
            args:
                user: maurosoft
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: good-meal-crud-service
        container_name: good-meal-crud-service
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./crud-service:/var/www
        networks:
            - good-meal

    db:
        image: mysql:5.7
        env_file:
            - ./crud-service/.env
        container_name: good-meal-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - good-meal

    nginx:
        image: nginx:alpine
        container_name: good-meal-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./crud-service:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - good-meal

networks:
    good-meal:
        driver: bridge
